#Dockercompose 신택스 버젼
version : "3.8"
#실행해야 할 모든 컨테이너들
services:
  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001 #debug port
    environment:
      #Paketo Buildpack 환경 변수, 할당 스레스 수 지정, servelt default는 250
      - BPL_JVM_THREAD_COUNT=50
      # debug 모드 활성화 및 포트 지정
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      #db 연결정보
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      #testdata 스프링 프로필 활성화
      - SPRING_PROFILES_ACTIVE=testdata

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=polardb_catalog
